env:
  browser: true
  es2022: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - 2
    - tab
  curly:
    - 2
    - all
  lines-around-comment:
    - 2
    - beforeBlockComment: true
      afterBlockComment: true
      beforeLineComment: true
      afterLineComment: true
      allowBlockStart: true
      allowBlockEnd: true
      allowObjectStart: true
      allowObjectEnd: true
      allowArrayStart: true
      allowArrayEnd: true
  max-len:
    - 2
    - code: 80
      ignoreUrls: true
  no-confusing-arrow:
    - 2
    - allowParens: false
  no-mixed-operators: 2
  no-tabs:
    - 2
    - allowIndentationTabs: true
  no-unexpected-multiline: 2
  quotes:
    - 2
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  import/no-unresolved: webpack
  react/prop-types: 0
  react/jsx-filename-extension:
    - 2
    - extensions: ['.js', '.jsx']
ignorePatterns: ['node_modules/', 'dist/']
