extends: [stylelint-config-standard, stylelint-config-prettier]
customSyntax: postcss-less
rules:
  no-empty-source: null
  property-no-unknown:
    - true
    - ignoreProperties: [font-smooth]
ignoreFiles: ['**/node_modules/', 'dist/', 'coverage/']
