extends: [stylelint-config-standard, stylelint-config-prettier]
processors: [postcss-less]
overrides:
  - files:
      - '**/style/**/*.less'
  - customSyntax: postcss-less
ignoreFiles: ['node_modules/', 'dist/']
allRules: []
