name: Deployment pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
  format:
    needs: [setup]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.17.0
          cache: 'yarn'
          cache-dependency-path: '/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Perf format
        run: yarn run format
  style:
    needs: [format]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.17.0
          cache: 'yarn'
          cache-dependency-path: '/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Check Style
        run: yarn run style
  lint:
    needs: [format]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.17.0
          cache: 'yarn'
          cache-dependency-path: '/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Lint Perse
        run: yarn run lint
  build:
    needs: [style, lint]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.17.0
          cache: 'yarn'
          cache-dependency-path: '/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Builder
        if: ${{ github.event_name == 'push' }}
        run: yarn run build
      - name: Redundant builds
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.17.0
          cache: 'yarn'
          cache-dependency-path: '/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Redundant builds
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Testing
        run: yarn run test

  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy with gh-pages
        if: ${{ github.event_name == 'push' }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
